[rendu]
warnock=0
zbuffer=0
tiles=1

[resolution]
screen_width=1536
screen_height=900

[modele]
model_path=./ressources/susaneHiDef.obj

[camera]
position_x=5.0
position_y=5.0
position_z=5.0
target_x=0.0
target_y=0.0
target_z=0.0
fov=25.0
near=0.01
far=1000.0

[culling]
frustum_culling=1
backface_culling=1

[lumiere]
dir_x=1.0
dir_y=1.0
dir_z=-1.0
ambient_light=0.2
diffuse_light=0.6
specular_light=1.5
shininess_light=128.0
refl1=0.15 ;refl1=0.8 ;refl1=0.15
refl2=0.5 ;refl2=0.5 ;refl2=0.5

[textures]
enabled=1
diffuse_tex=./ressources/wood_floor_deck_diff_2k.png
normal_tex=./ressources/wood_floor_deck_nor_gl_2k.png

[environmentMap]
enableEnvMap=1
envMap=./ressources/bell_tower.jpg

[skyBox]
blur=0
radius=10

[DepthOfField]
dof=1
;sqrt(10²+10²+10²) ≈ 17
;focalDistance=-17.5
focalDistance=-8.5
focalRange=3.0
maxBlurRadius=10

[tiles]
num_threads=8
tile_size=128
max_tri_per_tile=20000
debug_tiles=0

[warnock]
tree_depth=11
contour_arbre=1
max_poly=10000